# Generated by Django 4.0.4 on 2022-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phimodel',
            name='prescription',
            field=models.ImageField(null='True', upload_to='user_image/'),
        ),
    ]
