# Generated by Django 4.0.4 on 2022-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_phimodel_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='phimodel',
            name='bmi',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='body_temp',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='bp',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='oxyzen',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='pulserate',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='sugar',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
