# Generated by Django 4.0.4 on 2022-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_phimodel_bmi_remove_phimodel_body_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='file_key',
        ),
    ]
