# Generated by Django 4.0.4 on 2022-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_devicemodel_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='nm_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='pt_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
