# Generated by Django 4.0.4 on 2022-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_devicemodel_nm_key_devicemodel_pt_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='body_temp',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='oxyzen',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='pulserate',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='sugar',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='bmi',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='body_temp',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='bp',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='oxyzen',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='pulserate',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='phimodel',
            name='sugar',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
