# Generated by Django 4.0.4 on 2022-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_devicemodel_bmi_remove_devicemodel_body_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phimodel',
            name='device_name',
            field=models.CharField(default='Pending', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
